### ISSUE TITLE
Can not track transaction 

### ISSUE THREAD

**Issue by malovis** [forbole/big-dipper#468] opened 2021-02-20 14:38 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kwunyeung** [comment] 2021-02-20 18:11
Thank you for the report. This is a duplicate of #456.

**Closed by kwunyeung** 2021-02-20 18:11 UTC
