### ISSUE TITLE
BIGDIPPER PROBLEM

### ISSUE THREAD

**Issue by jack091069** [forbole/big-dipper#459] opened 2021-02-19 08:13 UTC
I SENT ON YESTERDAY SOME ATOM FROM COINBASE TO MY PRIVATE ATOMIC WALLET AND I NEVER RECEIVED THEM.

WHEN I CHECKED THE TRANSACTION I HAVE THE FOLLOWING MESSAGE ON BIGDIPPER: 

We're sorry - something's gone wrong.

Please try to refresh the page and see if the problem is gone. If the problem keeps happening, please consider filing a Github issue.

I WOULD LIKE TO RETRIEVE MY CRYPTO.

THANKS AND REGARDS

**Comment by pdubb12003** [comment] 2021-02-19 18:31
Same

**Comment by kwunyeung** [comment] 2021-02-20 00:26
Thank you for the report. This is a duplicate of #456.

**Closed** 2021-02-20 00:26 UTC
Labels: duplicate
