### ISSUE TITLE
When a delegator cast a vote its power isn't showed

### ISSUE THREAD

**Issue by RaulBernal** [forbole/big-dipper#508] opened 2021-04-27 09:41 UTC
**Describe the bug**
At the detailed proposal page the validator power is showed correctly but not for delegators
However the total power of both (validators + delegators is showed).

**To Reproduce**
1. Subit a proposal
2. Vote it with a delegator and also with a validator
3. Look the proposal page and compare power collumn

**Expected behavior**
Expecting view the power % and amount of each delegator

**Screenshots**
![image](https://user-images.githubusercontent.com/3751926/116220957-7019ee00-a74d-11eb-86d5-a4ff20d23346.png)

**Comment by kwunyeung** [comment] 2021-04-28 11:05
Closing as it's a duplicate of #486

**Closed by kwunyeung** 2021-04-28 11:05 UTC
