### ISSUE TITLE
genesisFile seems to require an https hosted file. What about http, or local file access?

### ISSUE THREAD

**Issue by njmurarka** [forbole/big-dipper#271] opened 2020-02-05 23:47 UTC
I immediately found it hard to use the software because I had to find a way to host the genesis.json file on an https server. It took me a long time and ultimately, as a test, I used pastebin, which is not at all ideal and only short term. 

I would like to be able to refer to the genesis file either locally on the same file system or at an http or https endpoint.

Thoughts?

**Comment by kwunyeung** [comment] 2020-02-07 08:36
It's currently getting from an external url. I'm not sure if you can do with `file://` for local file. `http` or `https` should be fine. You may create the genesis file on [gist](https://gist.github.com).

**Comment by njmurarka** [comment] 2020-02-07 10:05
Thanks for the feedback and apologies -- not complaining or anything. Definitely would be better to have some more documentation whenever possible. I will try to run it without the genesis file. So basically, if I do not include the genesis file, how does the user experience change?

**Comment by kwunyeung** [comment] 2020-02-11 15:31
Should not have big difference as you are not waiting the network to start. I especially built that (and the count down) for people to see the list of validators when they are waiting for the network start. The read genesis function will read some more params from the genesis file but we haven't had the components displaying them yet. However, all of those params can be read from the chain directly.

**Comment by njmurarka** [comment] 2020-02-27 11:16
I suppose I could just point at the server's own "http://localhost:26657/genesis?" endpoint?

**Comment by kwunyeung** [comment] 2020-02-27 19:09
No it's not the same.

**Comment by njmurarka** [comment] 2020-02-27 19:11
Ok that explains why that did not work for me.

**Comment by kwunyeung** [comment] 2020-03-13 08:56
I close this now as the issue is tracked by #280

**Closed by kwunyeung** 2020-03-13 08:56 UTC
Labels: question
