### ISSUE TITLE
Blockchain fail

### ISSUE THREAD

**Issue by pdubb12003** [forbole/big-dipper#458] opened 2021-02-19 06:11 UTC
**Describe the bug**
Bought cosmos on Coinbase and sent to my Atomic wallet adress and didn't receive 
**To Reproduce**

**Expected behavior**
Please just fix whatever happened and hope my cosmos aren't lost thats a lot of money 
**Screenshots**
![image](https://user-images.githubusercontent.com/77612572/108465077-f1816b80-7246-11eb-8565-f2b83637c5d4.png)
![image](https://user-images.githubusercontent.com/77612572/108465093-fb0ad380-7246-11eb-9614-fb5509bba6d1.png)
![image](https://user-images.githubusercontent.com/77612572/108465111-01994b00-7247-11eb-9509-0d6bd5d612d3.png)
![image](https://user-images.githubusercontent.com/77612572/108465116-065dff00-7247-11eb-8a75-88100326d716.png)
**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
iPhone 10s stock browser safari 
**Additional context**

**Comment by kwunyeung** [comment] 2021-02-20 00:27
Thank you for the report. This is a duplicate of #456.

**Closed** 2021-02-20 00:27 UTC
Labels: duplicate
