### ISSUE TITLE
MongoError: E11000 duplicate key error collection

### ISSUE THREAD

**Issue by nebkas** [forbole/big-dipper#499] opened 2021-04-14 08:40 UTC
After a while running in production with heavy load I get a lot of these errors:

```
http://127.0.0.1:1317/cosmos/slashing/v1beta1/signing_infos/crocnclcons1etmwcct0klmw3nvr6dxwy2tn5g2whzuyvk0akf
Getting signing info of 'crocnclcons1etmwcct0klmw3nvr6dxwy2tn5g2whzuyvk0akf': MongoError: E11000 duplicate key error collection: bigdipper.validators index: address_1 dup key: { address: "CAF6EC616FB7F6E8CD83D34CE22973A214EB8B84" }
    at Function.create (/home/nebkas/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/error.js:57:12)
    at toError (/home/nebkas/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:123:22)
    at /home/nebkas/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/operations/common_functions.js:379:39
    at /home/nebkas/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/connection/pool.js:405:18
    at processTicksAndRejections (internal/process/task_queues.js:75:11) {
  [stack]: 'MongoError: E11000 duplicate key error collection: bigdipper.validators index: address_1 dup key: { address: "CAF6EC616FB7F6E8CD83D34CE22973A214EB8B84" }\n' +
    '    at Function.create (/home/nebkas/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/error.js:57:12)\n' +
    '    at toError (/home/nebkas/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:123:22)\n' +
    '    at /home/nebkas/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/operations/common_functions.js:379:39\n' +
    '    at /home/nebkas/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/connection/pool.js:405:18\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:75:11)',
  [message]: 'E11000 duplicate key error collection: bigdipper.validators index: address_1 dup key: { address: "CAF6EC616FB7F6E8CD83D34CE22973A214EB8B84" }',
  driver: true,
  name: 'MongoError',
  index: 0,
  code: 11000,
  keyPattern: { address: 1 },
  keyValue: { address: 'CAF6EC616FB7F6E8CD83D34CE22973A214EB8B84' },
  [futureStack]: 'MongoError: E11000 duplicate key error collection: bigdipper.validators index: address_1 dup key: { address: "CAF6EC616FB7F6E8CD83D34CE22973A214EB8B84" }\n' +
    '    at Function.create (/home/nebkas/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/error.js:57:12)\n' +
    '    at toError (/home/nebkas/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:123:22)\n' +
    '    at /home/nebkas/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/operations/common_functions.js:379:39\n' +
    '    at /home/nebkas/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/connection/pool.js:405:18\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:75:11)',
  [errmsg]: [Getter],
  [errorLabels]: [Getter]

```
On my test setup with the same tarball and a very low load it never happens. 

Some Ideas?

**Comment by kwunyeung** [comment] 2021-04-21 06:44
@nebkas Looks like it's trying to insert a 2nd signing-info record with the same consensus address. Do you see a duplicate of the following log?

```
http://127.0.0.1:1317/cosmos/slashing/v1beta1/signing_infos/crocnclcons1etmwcct0klmw3nvr6dxwy2tn5g2whzuyvk0akf
```

**Comment by nebkas** [comment] 2021-04-21 08:08
After I changed the partition for mongodb to XFS, the error no longer occurred. runs stable now.

**Closed** 2021-04-21 08:08 UTC
